[book]
authors = ["Kazuaki Ishiguro"]
language = "en"
multilingual = false
src = "src"
title = "zkC.R.E.A.M docs"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/zkcream/docs"
site-url = "https://zkcre.am/docs"